security:
    hide_user_not_found: false
    
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Cerad\Bundle\AccountBundle\Entity\AccountUser: 
            id: cerad_account.user_encoder

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass,  roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    
        cerad_account_user_provider:
            id: cerad_account.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            pattern:   ^/
            anonymous: ~
            
            logout:
                path:   cerad_account_logout
                target: cerad_account_welcome
                
            form_login:
                provider:            cerad_account_user_provider
                login_path:          cerad_account_login
                check_path:          cerad_account_login_check
                default_target_path: cerad_account_home

                username_parameter:  cerad_account_signin[username]
                password_parameter:  cerad_account_signin[password]
                csrf_parameter:      cerad_account_signin[_token]
                csrf_provider:       form.csrf_provider
                intention:           authenticate
 
    access_control:
        # - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
