
cerad_account_index:
  path: /
  defaults:  { _controller: CeradAccountBundle:Main:index }

cerad_account_welcome:
  path: /welcome
  defaults:  { _controller: CeradAccountBundle:Main:welcome }
  
cerad_account_home:
  path: /home
  defaults:  { _controller: CeradAccountBundle:Main:home }
  
cerad_account_register:
  path: /register
  defaults:  { _controller: CeradAccountBundle:Registration:register }

