
cerad_account_index:
  path: /
  defaults:  { _controller: CeradAccountBundle:Main:index }

cerad_account_welcome:
  path: /welcome
  defaults:  { _controller: CeradAccountBundle:Main:welcome }
  
cerad_account_home:
  path: /home
  defaults:  { _controller: CeradAccountBundle:Main:home }
  
cerad_account_login:
  path: /login
  defaults:  { _controller: CeradAccountBundle:Security:login }
  
cerad_account_login_check:
  path: /login-check
  defaults:  { _controller: CeradAccountBundle:Security:check }  # Throws exception
    
cerad_account_logout:
  path: /logout
  defaults:  { _controller: CeradAccountBundle:Security:logout } # Throes exception
    
cerad_account_register:
  path: /register
  defaults:  { _controller: CeradAccountBundle:Registration:register }

