Cerad\Bundle\AccountBundle\Entity\AccountUser:
    type:  entity
    table: account_user
    
    id:
        id:
            type:   string
            length: 40
            generator: { strategy: NONE }
    
    oneToMany:

        identifiers:
            targetEntity: AccountIdentifier
            mappedBy:     account
            cascade:      ['all']
           
    fields:
    
        name:
            column:   name
            type:     string
            length:   80
            nullable: true
            
        personId:
            column:   person_id
            type:     string
            length:   40
            nullable: true
            
        personNo:
            column:   person_no
            type:     boolean
           
        createdOn:
            column: created_on
            type:   datetime
